# Generated by Django 3.2.11 on 2022-01-19 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=50, verbose_name='Название мероприятия')),
                ('start_time', models.DateField(auto_now=True, verbose_name='Время начала события')),
                ('party_duration', models.IntegerField(verbose_name='Продолжительность мероприятия')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=50, verbose_name='Название плейлиста')),
                ('max_count_track', models.IntegerField(verbose_name='Максимальное количество записей')),
                ('party_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.party', verbose_name='Название мероприятия')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=100, verbose_name='Название трека')),
                ('track_url', models.URLField(verbose_name='Ссылка на трек')),
                ('track_rate', models.IntegerField(verbose_name='Рейтинг трека')),
                ('playlist_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.playlist', verbose_name='Название трека')),
            ],
        ),
    ]
