# Generated by Django 3.2.11 on 2022-01-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='party_duration',
        ),
        migrations.RemoveField(
            model_name='party',
            name='start_time',
        ),
        migrations.AddField(
            model_name='playlist',
            name='start_time',
            field=models.DateField(auto_now=True, verbose_name='Время открытия'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='time_expired',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время закрытия'),
        ),
    ]
