# Generated by Django 3.2.11 on 2022-01-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_playlist_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_singer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя исполнителя'),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_rate',
            field=models.IntegerField(default=0, verbose_name='Рейтинг трека'),
        ),
    ]
